# NUMPY

In [1]:
## CREATE A DATA SET OF NUMPY
##import numpy

In [2]:
import numpy as np

## 1D Array

In [3]:
d=np.array([2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40])


### Attributes of arrays

#### 1 - dtype
#### 2 - ndim
#### 3 - size
#### 4 - shape

In [4]:
## dtype - to chek the data type of the array
d.dtype

dtype('int32')

In [5]:
## ndim - the dimension of the array
d.ndim

1

In [6]:
## size - to check the arrays size 
d.size

20

In [7]:
## shape - 
d.shape

(20,)

## index location

In [8]:
d[2]

6

In [9]:
d[10]

22

In [10]:
d[18]

38

## Multi dimensional array

In [11]:
d_2d=np.array([[2,4,6,8,10,12,14,16,18,20],[22,24,26,28,30,32,34,36,38,40]])

In [12]:
d_2d

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32, 34, 36, 38, 40]])

In [13]:
d_2d.dtype

dtype('int32')

In [14]:
d_2d.ndim

2

In [15]:
d_2d.size

20

In [16]:
d_2d.shape

(2, 10)

In [17]:
d_2d[0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [18]:
d_2d[1]

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [19]:
d_2d[0][3]

8

In [20]:
d_2d[1][3]

28

## Another type of multi dimensional array

In [21]:
array_2=np.array([[[2,4,6,8,10,12,14,16,18,20]]])

In [22]:
array_2

array([[[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]]])

In [23]:
array_2.shape

(1, 1, 10)

## First element in first array

In [24]:
d_2d[0][0]

2

## second element in second array

In [25]:
d_2d[1][1]

24

## Lets change its data type into float 

In [26]:
d_2d = np.array([[2,4,6,8,10,12,14,16,18,20],[22,24,26,28,30,32,34,36,38,40]],dtype=float)

In [27]:
d_2d

array([[ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.],
       [22., 24., 26., 28., 30., 32., 34., 36., 38., 40.]])

## lets create a bigger array

In [28]:
d_bigger = np.array([
    [1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],
    [4,4,4,4,4],[5,5,5,5,5],[6,6,6,6,6],
    [6,6,6,6,6],[7,7,7,7,7],[8,8,8,8,8]
],dtype=float)
d_bigger

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8.]])

In [29]:
d_bigger.shape

(9, 5)

In [30]:
d_bigger[1][1]

2.0

## Filling arrays

In [31]:
d_bigger=np.full((1,2,3),7)

In [32]:
d_bigger

array([[[7, 7, 7],
        [7, 7, 7]]])

## zero and ones

In [33]:
d_zeros=np.zeros((3,3))

In [34]:
d_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
d_ones=np.ones((1,2,3,4,5))

In [36]:
d_ones

array([[[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]]])

In [37]:
e=np.empty((3,3,3))

In [38]:
e

array([[[1.21458722e-311, 1.21458727e-311, 0.00000000e+000],
        [0.00000000e+000, 1.33511018e-306, 1.15998412e-028],
        [4.31603868e-080, 1.94919985e-153, 1.35717430e+131]],

       [[9.42210349e-096, 1.12947740e-095, 8.51685748e-096],
        [1.03895280e-095, 7.71472562e+140, 6.01347002e-154],
        [2.99938296e-067, 2.99939428e-067, 1.96567191e-062]],

       [[1.96567933e-062, 1.28823247e-057, 1.06239598e-153],
        [3.98472821e+252, 1.06244660e-153, 9.78750380e+199],
        [6.97843734e+252, 9.11792863e-307, 3.49699467e-317]]])

## ranges